version: '3.7'

services:
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6400'
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
